config/routes.rb
Bydmmblog::Application.routes.draw do
  resources :tags

  devise_for :users

  resources :blogs
  
  match 'tagblog/:tag' => 'blogs#tagblog' , :as => :tagblog
  
  

  root :to => 'blogs#index'

end

app/models/ability.rb
# -*- encoding : utf-8 -*-
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    case user.role
      when 'admin'
        can :manage, :all
      else
        can :read, :all
        can :tagblog, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
# -*- encoding : utf-8 -*-
class Blog < ActiveRecord::Base
  attr_accessible :content, :title, :tags, :tag_ids
  has_many :tags
  has_and_belongs_to_many :tags
  
  def self.find_by_tag(tag_name)
    Tag.find_by_name(tag_name).try(:blogs)
  end
end

app/models/tag.rb
# -*- encoding : utf-8 -*-
class Tag < ActiveRecord::Base
  belongs_to :blog
  attr_accessible :name, :blogs
  has_and_belongs_to_many :blogs
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body
  
  ROLES = %w[admin moderator author banned]
  
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_seo_meta
  def set_seo_meta(title = '',meta_keywords = '', meta_description = '')
    if title.length > 0
      @page_title = "#{title} - 不科学的技术小站"
    else
      @page_title = "不科学的技术小站"
    end
    @meta_keywords = meta_keywords
    @meta_description = meta_description
  end
  
  def markdown(text)
    options = {   
        :autolink => true, 
        :space_after_headers => true,
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :hard_wrap => true,
        :strikethrough =>true
      }
    markdown = Redcarpet::Markdown.new(HTMLwithCodeRay,options)
    markdown.render(h(text)).html_safe
  end

  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      #CodeRay.scan(code, language).div(:tab_width=>2)
    end
  end
  
end

app/controllers/blogs_controller.rb
# -*- encoding : utf-8 -*-

class BlogsController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb :index, :root_path
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order('id DESC').all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end
  
  def tagblog
    @blogs = Blog.find_by_tag(params[:tag])
    self.set_seo_meta(params[:tag],'','');
    respond_to do |format|
      format.html # tagblog.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    self.set_seo_meta(@blog.title, BlogsHelper.join_tags(@blog), seo(@blog.content));
    add_breadcrumb @blog.title, blogs_path(@blog)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: '成功创建博客' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: '博客成功更新' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
  
  private
    def seo(text)
      moshi = /\<\!\-\- more \-\-\>/
      pre = moshi.match(text).try(:pre_match)
      pre = pre ? pre : text
    end
    
end

app/controllers/tags_controller.rb
# -*- encoding : utf-8 -*-
class TagsController < ApplicationController
  load_and_authorize_resource
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: '成功创建标签.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: '成功更新标签.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  
  def morebreak(text)
    moshi = /\<\!\-\- more \-\-\>/
    pre = moshi.match(text).try(:pre_match)
    pre = pre ? pre : text
  end
  
  def markdown(text)
    options = {   
        :autolink => true, 
        :space_after_headers => true,
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :hard_wrap => true,
        :strikethrough =>true
      }
    markdown = Redcarpet::Markdown.new(HTMLwithCodeRay,options)
    markdown.render(h(text)).html_safe
  end
  
  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:tab_width=>2)
    end
  end
  
end

app/helpers/blogs_helper.rb
# -*- encoding : utf-8 -*-
module BlogsHelper
  
  def join_tags(blog)
    blog.tags.map { |t| t.name }.join(", ") 
  end
  
  def self.join_tags(blog)
    blog.tags.map { |t| t.name }.join(", ") 
  end

end

app/helpers/tags_helper.rb
# -*- encoding : utf-8 -*-
module TagsHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for @blog do |blog_form| %>
  <%= blog_form.input :title %>
  <%= blog_form.association :tags %>
  <div class="control-group">
    <div class="controls">
      <%= link_to '新建标签', new_tag_path, :target => "_blank " %>
    </div>
  </div>
  <%= blog_form.kindeditor :content, :filterMode => false, :window_onload => true %>
  <div class="btn-toolbar">
    <%= blog_form.button :submit %>
  </div>
<% end %>

app/views/blogs/_tags.html.erb
<div class="widgets blocks">
  <h5>标签</h5>
  <ul>
    <% Tag.all.each do |tag| %>
      <li><%= link_to tag.name, tagblog_path(tag.name) %></li>
    <% end %>
  </ul>      
</div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="row">
  <span class="span8">
    <div class="bloglist blocks">
      <% @blogs.each do |blog| %>
        <h2><%= link_to blog.title, blog %></h2>
        <div><%= morebreak(blog.content).html_safe %></div>
      
        <div>
          <% if can? :read, @blog %>
          <span><%= link_to '显示全文', blog %></span>
          <% end %>
          <% if can? :edit, @blog %>
          <span><%= link_to '编辑', edit_blog_path(blog) %></span>
          <% end %>
          <% if can? :destroy, @book %>
          <span>
            <%= link_to '删除', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
          </span>
          <% end %>
        </div>
        <hr />
      <% end %>
    </div>
    
  </span>
  <span class="span4">
    
    <div class="widgets blocks">
      <h5>最新文章</h5
      <ul>
        <% @blogs.each do |blog| %>
          <li><%= link_to blog.title, blog %></li>
        <% end %>
      </ul>      
    </div>
    <%= render 'tags' %>
    <% if can? :edit, @blog %>
    <div class="widgets blocks">
      <%= link_to '新建博客', new_blog_path %>
    </div>
    <% end %>
  </span>
</div>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="blocks blog">
  <div class="page-header">
    <h1><%= @blog.title %>
      <small><%= join_tags(@blog) %></small>
    </h1>
    <!-- JiaThis Button BEGIN -->
    <div class="jiathis_style" style="height:30px;" >
    	<span class="jiathis_txt">分享到：</span>
    	<a class="jiathis_button_tools_1"></a>
    	<a class="jiathis_button_tools_2"></a>
    	<a class="jiathis_button_tools_3"></a>
    	<a class="jiathis_button_tools_4"></a>
    	<a href="http://www.jiathis.com/share?uid=1588775" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank">更多</a>
    	<a class="jiathis_counter_style"></a>
    </div>
    <script type="text/javascript">
    var jiathis_config = {data_track_clickback:'true'};
    </script>
    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1588775" charset="utf-8"></script>
    <!-- JiaThis Button END -->
  </div>

  <div><%= @blog.content.html_safe %></div>

  <p>
    <span><%= link_to '返回上页', blogs_path %></span>
    <% if can? :edit, @blog %>
    <span><%= link_to '编辑', edit_blog_path(@blog) %></span>
    <% end %>
    <% if can? :destroy, @book %>
    <span>
      <%= link_to '删除', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </span>
    <% end %>
  </p>



  <hr />
  <!-- UY BEGIN -->
  <div id="uyan_frame"></div>
  <script type="text/javascript" id="UYScript" src="http://v1.uyan.cc/js/iframe.js?UYUserId=1588775" async=""></script>
  <!-- UY END -->
  <hr />
  <!-- UJian Button BEGIN -->
  <div class="ujian-hook"></div>
  <script type="text/javascript" src="http://v1.ujian.cc/code/ujian.js?uid=1588775"></script>
  <a href="http://www.ujian.cc" style="border:0;"><img src="http://img.ujian.cc/pixel.png" alt="友荐云推荐" style="border:0;padding:0;margin:0;" /></a>
  <!-- UJian Button END -->  
</div>

app/views/blogs/tagblog.html.erb
<div class="row">
  <span class="span8">
    <div class="bloglist blocks">
      <% if @blogs %>
        <% @blogs.each do |blog| %>
          <h2><%= link_to blog.title, blog %></h2>
          <div><%= morebreak(blog.content).html_safe %></div>
      
          <div>
            <% if can? :read, @blog %>
            <span><%= link_to '显示全文', blog %></span>
            <% end %>
            <% if can? :edit, @blog %>
            <span><%= link_to '编辑', edit_blog_path(blog) %></span>
            <% end %>
            <% if can? :destroy, @book %>
            <span>
              <%= link_to '删除', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
            <% end %>
          </div>
          <hr />
        <% end %>
      <% else %>
        <h2>本条目暂无博客</h2>
      <% end %>
    </div>
    
  </span>
  <span class="span4">
    
    <div class="widgets blocks">
      <h5>最新文章</h5>
      <ul>
        <% if @blogs %>
          <% @blogs.each do |blog| %>
            <li><%= link_to blog.title, blog %></li>
          <% end %>
        <% else %>
          <li>本条目暂无博客</li>
        <% end %>
      </ul>      
    </div>
    <%= render 'tags' %>
    <% if can? :edit, @blog %>
    <div class="widgets blocks">
      <%= link_to '新建博客', new_blog_path %>
    </div>
    <% end %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @page_title %></title>
    <meta name="keywords" content="<%= @meta_keywords %>" />
    <meta name="description" content="<%= @meta_description %>" />
    
    <%= csrf_meta_tags %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
		
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>"><%= t('sitename') %></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to t("index"), root_path  %></li>
            </ul>
            
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                欢迎，<%= current_user.email %> 
                <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                <li><%= link_to '退出登录', destroy_user_session_path, :method => :delete %></li>
                </ul>
                </li>
                <% else %>
                <li><%= link_to "注册", new_user_registration_path %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to "登陆", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    <div class="container bootstrapbugs">
      <%= render_breadcrumbs %>
      <%= bootstrap_flash %>
      <%= yield %>
      <footer>
        <div class="icp"><a rel="external nofollow" target="_blanck" href="http://www.miibeian.gov.cn/">鄂ICP备12016882号</div>
      </footer>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-29763015-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>

app/views/tags/_form.html.erb
<%= simple_form_for @tag do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>